### ISSUE TITLE
Gaining a level crashes game

### ISSUE THREAD

**Issue by amaryllisninja** [amaryllisninja/python_text_rpg#12]
Do you ATTACK, use an ITEM, or FLEE?  attack
Jo hit for 6 points of damage!
Giant Snake has died.
You have killed Giant Snake.
Traceback (most recent call last):
  File "C:\Users\graybilla\Documents\Personal\python_text_rpg\gameFile.py", line 82, in <module>
    gameActions.checkAction(name)
  File "C:\Users\graybilla\Documents\Personal\python_text_rpg\gameActions.py", line 498, in checkAction
    atk.attack(action, name)
  File "C:\Users\graybilla\Documents\Personal\python_text_rpg\atk.py", line 113, in attack
    lvl.addXP(charName, victim)
  File "C:\Users\graybilla\Documents\Personal\python_text_rpg\leveling.py", line 18, in addXP
    checkLevelUp(name, oldLevel, newLevel)
  File "C:\Users\graybilla\Documents\Personal\python_text_rpg\leveling.py", line 33, in checkLevelUp
    print("You have leveled up!\nYou are now level " + newLevel + "\n\n")
TypeError: can only concatenate str (not "int") to str

**Comment by amaryllisninja** [comment]
This issue blocks leveling up process, ie, the character becomes level 1, but then the game crashes before character leveling up attribute assignments occur

**Comment by amaryllisninja** [comment]
Added code to write over old XP pickle at start of game.

**Comment by amaryllisninja** [comment]
Leveling now works, but XP points don't show up when looking at self.
